labyrinth:
  allowed-origins:
    - http://localhost:8081
    - http://localhost:63342
    - http://192.168.1.10:8001
    - http://192.168.1.10:8081
    - http://192.168.1.11:8081
  game-flush-period: ${GAME_FLUSH_PERIOD:50}

server:
  compression:
    enabled: true
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:30d}

spring:
  profiles:
    active: local
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
